config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations",
  }
  devise_scope :user do
    get "users/sign_up_guide", to: "users/registrations#new_guide"
    get "users/sign_up_tourist", to: "users/registrations#new_tourist"
  end

  resources :tours, only: [:index, :show, :new, :create] do
    collection do
      get :search
      get :accept_call
    end
    member do
      post :schedule
    end
  end

  get "/get-the-guide", to: 'home#get_the_guide'
  root 'home#show'
end

app/models/tour.rb
class Tour
  include Mongoid::Document

  mount_uploader :tour_image, TourImageUploader

  field :title, type: String
  field :country, type: String
  field :city, type: String
  field :language, type: String
  field :date, type: Time
  field :latitude, type: Float
  field :longitude, type: Float

  belongs_to :owner, class_name: 'User'

  def owner
    @owner ||= User.find_by(id: owner_id)
  end

  def has_coords?
    latitude && latitude != 0 && longitude && longitude != 0
  end
end

app/models/tour_link.rb
class TourLink
  STATES = %w(scheduled started finished)

  include Mongoid::Document

  field :state

  belongs_to :tour
  embedded_in :tourist, class_name: 'User'

  STATES.each { |s| define_method("#{s}?") { state == s } }
end

app/models/user.rb
class User
  ROLES = {
    guide: 1,
    tourist: 2,
  }

  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  field :provider, type: String
  field :uid, type: String

  field :name, type: String
  field :role, type: Integer, default: 2
  field :kandy_register_response, type: Hash

  embeds_many :tour_links, inverse_of: :tourist

  index({provider: 1, uid: 1})

  after_create :register_in_kandy

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
    end
  end

  def register_in_kandy
    uid = email.gsub('@', '').gsub('.', '')[0..14]
    key = 'DATffefa3a877d644e09b4985e61abbdce8'
    url = 'https://api.kandy.io/v1.2/domains/users/user_id'
    res = RestClient.post "#{url}?key=#{key}&user_id=#{uid}&user_country_code=US", {}
    set kandy_register_response: JSON.parse(res)
  end

  def guide?
    role == self.class::ROLES[:guide]
  end

  def tourist?
    role == self.class::ROLES[:tourist]
  end

  def tours
    if guide?
      Tour.where owner: self
    else
      tour_links.map &:tour
    end
  end

  def kandy_id
    return unless kandy_register_response
    self['kandy_register_response'].fetch('result', {}).fetch('full_user_id', nil);
  end

  def kandy_password
    return unless kandy_register_response
    self['kandy_register_response'].fetch('result', {}).fetch('user_password', nil);
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) ||
      (resource.guide? ? tours_path : root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end

  def get_the_guide
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :authenticate_user!, except: [:search]

  def index
    @tours = current_user.tours
  end

  def search
    attrs = {}
    [:country, :language, :date].each do |field|
      attrs[field] = params[field] if params[field].present?
    end
    if attrs[:date].present?
      date = Time.parse attrs[:date]
      attrs[:date] = {
        '$gte' => date.beginning_of_day,
        '$lt' => date.end_of_day,
      }
    end
    @tours = Tour.where(attrs)
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new params[:tour].to_hash.merge(owner: current_user)
    if @tour.save
      redirect_to tour_path(@tour)
    else
      render :new
    end
  end

  def schedule
    current_user.tour_links.create tour: Tour.find(params[:id]), state: 'scheduled'
    redirect_to tours_path
  end

  def show
    @tour = Tour.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, only: [:create]

  def new_guide
    build_resource({role: User::ROLES[:guide]})
    set_minimum_password_length
    respond_with self.resource
  end

  def new_tourist
    build_resource({role: User::ROLES[:tourist]})
    set_minimum_password_length
    respond_with self.resource
  end

  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      redirect_path = params[:user][:role].to_i == User::ROLES[:guide] ? users_sign_up_guide_path : users_sign_up_tourist_path
      redirect_to redirect_path
    end
  end

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push :name, :role
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def country_opts_for_select
    Tour.distinct(:country).map do |key|
      label = ISO3166::Country.new(key).to_s.presence || key
      [key, label]
    end
  end

  def city_opts_for_select
    Tour.distinct(:city).map { |key| [key, key] }
  end

  def language_opts_for_select
    Tour.distinct(:language).map do |key|
      label = ISO_639::find(key).try(:english_name) || key
      [key, label]
    end
  end

  def current_user_tourist?
    current_user && current_user.tourist?
  end

  def current_user_guide?
    current_user && current_user.guide?
  end

  def tour_scheduled?(tour)
    current_user && current_user.tour_links.find_by(tour: tour).present?
  end
end

app/views/home/get_the_guide.html.erb
<div class="get-the-guide">
	<div class="container content-container">
		<div class="row">
			
			<div class="col-sm-12 tour-item" style="background-image: url('images/italian-building-italy-destroyed.jpg')">
				<giv class="col-xs-7">
					<h2>Italian trip</h2>
				</giv>
				<div class="col-xs-5 text-right">
					<%= image_tag("black-and-white-man-person-eyes.jpg", :alt => "John", :class => 'img-responsive img-circle') %>
					<h4><small>Guide name:</small> John Madisson</h4>
					<span class="label label-default">Price: $25</span>
					<span class="label label-default">Duration: 2h 30m</span>
				</div>
			</div>

		</div>
	</div>
</div>

app/views/home/show.html.erb
<div class="home-page__show">
  <div class="container content-container">
    <%= form_tag search_tours_path, method: :get do %>
      <div class="form-group home-inputs">
        <label for="country">Country</label>
        <%= select_tag :country, options_from_collection_for_select(country_opts_for_select, :first, :last),
          class: 'form-control' %>
      </div>
      <div class="form-group home-inputs">
        <label for="city">City</label>
        <%= select_tag :city, options_from_collection_for_select(city_opts_for_select, :first, :last),
          class: 'form-control' %>
      </div>
      <div class="form-group home-inputs">
        <label for="language">Language</label>
        <%= select_tag :language, options_from_collection_for_select(language_opts_for_select, :first, :last),
          class: 'form-control' %>
      </div>
      <div class="form-group home-inputs">
        <label for="date">Date</label>
        <input type="date" class="form-control" id="date" name="date">
      </div>

      <%= submit_tag 'Get the Guide', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="http://bootswatch.com/paper/bootstrap.min.css">

  <title>Touragogo</title>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Guide Me</a>
    </div>

    <div class="collapse navbar-collapse" id="main-menu">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to 'My Tours', tours_path %></li>
          <li><%= link_to 'Add tour', new_tour_path, class: '' if current_user_guide? %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a><span id='online-status' class='label label-danger'>Offline</span></a></li>
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: 'DELETE' %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<%= yield %>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-xs-6">
            <div id="local-video" style="position: relative; z-index: 2; min-width: 100px; min-height: 70px;">
              <img src="http://www.noteblur.com/Content/Avatar/empty-avatar.jpg" alt="" class="img-responsive">
            </div>
          </div>
          <div class="col-xs-6">
            <div id="remote-video" style="position: relative; z-index: 2; min-width: 100px; min-height: 70px;">
              <img src="http://www.noteblur.com/Content/Avatar/empty-avatar.jpg" alt="" class="img-responsive">
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button id="reject" type="button" class="btn btn-default" data-dismiss="modal" onclick="rejectCall()">Reject</button>
        <button id="answer" type="button" class="btn btn-primary" onclick="answerCall()">Answer</button>
        <button id="hangout" type="button" class="btn btn-danger" style="display:none" onclick="endCall()">End call</button>
      </div>
    </div>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="https://kandy-portal.s3.amazonaws.com/public/javascript/kandy/2.4.1/kandy.js" ></script>
<script>
  <% if current_user %>
    $(function() {
      var fullUserId = '<%= current_user.kandy_id %>';
      var userPassword = '<%= current_user.kandy_password %>';
      var apiKey = 'DAK2dc941ec92254fad9cda939b8bb05de4';

      kandy.setup({
        remoteVideoContainer: document.getElementById('remote-video'),
        localVideoContainer: document.getElementById('local-video'),
        listeners: {
          callinitiated: function(call, callee){
            window.callId = call.getId();
            console.log("Call initiated with ", callee, "['", callId, "']. Ringing...");
          },
          callinitiatefailed: function(){
            alert('Call failed');
            console.log('onCallInitiateFailed,');
          },
          callincoming: function(call){
            window.callId = call.getId();
            console.log('onCallIncoming,');
            $('#myModal').modal({
              show: true,
              backdrop: false
            });
          },
          callanswered: function() { console.log('onCallAnswered,'); },
          callanswerfailed: function(){ console.log('onCallAnswerFailed,'); },
          callrejected: function() {
            alert('Call rejected!');
          },
          callended: function(){ console.log('onCallEnded,'); },
          callendfailed: function(){ console.log('onCallEndFailed,'); },
          callestablished: function(){ console.log('onCallEstablished,'); },
          callstatechanged: function(){ console.log('onCallStateChanged'); }
        },
        autoreconnect: true,
        registerforcalls: true,
        loglevel: 'debug'
      });

      kandy.login(apiKey, fullUserId, userPassword,
        function(token) {
          console.log('Kandy login succeeded, token: ', token);
          $('#online-status').html('Online');
          $('#online-status').addClass('label-success');
          $('#online-status').removeClass('label-danger');
        },
        function() {
          console.log('Kandy login failed');
        }
      );

      window.kandyCall = function(destination) {
        kandy.call.makeCall(destination, true);
      };

      window.endCall = function() {
        $('#myModal').modal({
          show: false
        });
        if (window.callId) {
          kandy.call.endCall(callId);
        }
      };

      window.answerCall = function() {
        kandy.call.answerCall(callId, true);
        $('#reject').hide(0);
        $('#answer').hide(0);
        $('#hangout').show(0);
      };

      window.rejectCall = function() {
        $('#myModal').modal({
          show: false
        });
        if (window.callId) {
          kandy.call.rejectCall(callId);
        }
      };
    });
  <% end %>
</script>

<script>
  window.callToGuide = function(id) {
    $('#reject').hide(0);
    $('#answer').hide(0);
    $('#hangout').show(0);

    $('#myModal').modal({
      show: true
    });

    kandyCall(id);
  }
</script>

</body>
</html>

app/views/tours/_tour.html.erb
<div class="col-sm-4 tour-item">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
        <%= tour.title %>
      </h3>
    </div>
    <div class="panel-body">
      <%= image_tag(tour.tour_image.url, alt: '', class: 'img-responsive') %>
      <%= image_tag("black-and-white-man-person-eyes.jpg", alt: "John", class: 'img-responsive img-circle') %>

      <div class="col-xs-12 text-center guide-info">
        <h5><small>Guide name:</small> John Madisson</h5>
        <% if current_user_tourist? %>
          <%= form_tag schedule_tour_path(tour.id) do %>
            <%= link_to 'Details', tour, class: "btn btn-primary btn-md" %>
            <% if tour_scheduled?(tour) %>
              <span class="label label-default">Scheduled</span>
            <% else %>
              <%= submit_tag 'Schedule tour', class: "btn btn-success btn-md" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="panel-footer text-center">
      <span class="label label-default">Price: $25</span>
      <span class="label label-default">Duration: 2h 30m</span>
    </div>
  </div>
</div>

app/views/tours/_tour_item.html.erb
<div class="col-sm-4 tour-item">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
        <%= link_to tour_item.title, tour_path(tour_item) %>
      </h3>
    </div>
    <div class="panel-body">
      <% if tour_item.has_coords? %>
        <img class="img-responsive" src="https://maps.googleapis.com/maps/api/staticmap?center=&zoom=13&size=500x500&maptype=roadmap&markers=color:red%7Clabel:C%7C<%= tour_item.latitude %>,<%= tour_item.longitude %>&key=AIzaSyCQo2TjlIearvQuC6ZXsFxAbUkZ-QCLVQs" alt="">
      <% end %>

      <div class="col-xs-12 text-center guide-info">
        <% if current_user and current_user != tour_item.owner %>
          <a onclick="callToGuide('<%= tour_item.owner.kandy_id %>')" class='btn btn-sm btn-success'>
            Call guide
          </a>
        <% end %>
        <%= link_to 'Details', tour_path(tour_item), :class => 'btn btn-primary btn-sm' %>
      </div>
    </div>
    <div class="panel-footer text-center">
      <span class="label label-default">Price: $25</span>
      <span class="label label-default">Duration: 2h 30m</span>
    </div>
  </div>
</div>

app/views/tours/accept_call.html.erb
<div class="container content-container">
  <div class="row">
    <div class="col-md-6">
      <%= image_tag('italian-building-italy-destroyed.jpg', alt: '', class: 'img-responsive') %>
    </div>
    <div class="col-md-6 text-center">
      <h2>Tour title</h2>
      <h4><small>Tourist:</small> John Smith</h4>
      <h4><small>Time:</small> 9:43 AM</h4>
      <a href="#" class="btn btn-success btn-lg">Accept call</a>
    </div>
  </div>
</div>

app/views/tours/create.html.erb
<form>
  <div class="form-group">
    <label for="title">Title</label>
    <input type="text" class="form-control" id="title" placeholder="Title">
  </div>

  <div class="form-group">
    <label for="country">Country</label>
    <select class="form-control" id="country" name="country">
      <option selected value="ua">Ukraine</option>
      <option value="gb">United Kingdom</option>
      <option value="it">Italy</option>
      <option value="fr">France</option>
    </select>
  </div>

  <div class="form-group">
    <label for="language">Language</label>
    <select multiple class="form-control" id="language" name="language">
      <option selected value="it">Italian</option>
      <option value="uk">Ukranian</option>
      <option value="en">English</option>
    </select>
  </div>

  <div class="form-group">
    <label for="cover">File input</label>
    <input type="file" id="cover">
  </div>

  <div class="form-group">
    <label for="date">Date</label>
    <input type="date" class="form-control" id="date" name="date">
  </div>

  <button class="btn btn-primary">Create your tour</button>
</form>

app/views/tours/index.html.erb
<div class="container content-container">
  <%= render partial: 'tour_item', collection: @tours %>
</div>

app/views/tours/new.html.erb
<div class="container content-container">
  <div class="row">
    <div class="col-md-6" id="map"></div>

    <div class="col-md-6" id="form">
      <%= form_for @tour, html:{class: 'form-horizontal'} do |f| %>
        <%= f.hidden_field :latitude %>
        <%= f.hidden_field :longitude %>
        <div class="form-group">
          <label for="title" class="col-sm-2 control-label">Title</label>
          <div class="col-sm-10">
            <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
          </div>
        </div>

        <div class="form-group">
          <label for="country" class="col-sm-2 control-label">Country</label>
          <div class="col-sm-10">
            <%= f.select :country, ISO3166::Country.all.map { |c| [c.name, c.alpha2] }, {}, {class: 'form-control'}%>
          </div>
        </div>

        <div class="form-group">
          <label for="country" class="col-sm-2 control-label">City</label>
          <div class="col-sm-10">
            <%= f.text_field :city, class: 'form-control', placeholder: 'City'  %>
          </div>
        </div>

        <div class="form-group">
          <label for="language" class="col-sm-2 control-label">Language</label>
          <div class="col-sm-10">
            <%= f.select :language, ISO_639::ISO_639_1.map { |c| [c.english_name, c.alpha2] }, {}, {class: 'form-control'}%>
          </div>
        </div>

        <div class="form-group">
          <label for="tour_image" class="col-sm-2 control-label">File input</label>
          <div class="col-sm-10">
            <%= f.file_field :tour_image %>
            <%= f.hidden_field :tour_image_cache %>
          </div>
        </div>

        <div class="form-group">
          <label for="date" class="col-sm-2 control-label">Date</label>
          <div class="col-sm-10">
            <input type="date" class="form-control" id="tour[date]" name="tour[date]">
          </div>
        </div>

        <%= f.submit 'Create your tour', class: 'btn btn-primary col-sm-offset-2' %>
      <% end %>
    </div>
  </div>
</div>

<script>
  var map;
  var mapContainer = document.getElementById('map');
  var form = document.getElementById('form');
  var marker;

  function initMap() {
    var defaultLocation = new google.maps.LatLng(40.69847032728747, -73.9514422416687);
    map = new google.maps.Map(mapContainer, {
      center: defaultLocation,
      zoom: 8
    });
    mapContainer.style.height = form.offsetHeight + 'px';

    google.maps.event.addListener(map, 'click', function(event) {
      placeMarker(map, event.latLng);
    });

    // Try W3C Geolocation (Preferred)
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        var currentLocation = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
        placeMarker(map, currentLocation);
        map.setCenter(currentLocation);
      }, function() {
        handleNoGeolocation();
      });
    } else {
      handleNoGeolocation();
    }

    var handleNoGeolocation = function() {
      map.setCenter(defaultLocation);
    };

    var placeMarker = function(map, coords) {
      document.getElementById('tour_latitude').value = coords.lat();
      document.getElementById('tour_longitude').value = coords.lng();
      if (marker) {
        marker.setPosition(coords);
      } else {
        marker = new google.maps.Marker({
          position: coords,
          map: map,
          draggable: true,
        });
      }
      map.setCenter(coords);
    };
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCQo2TjlIearvQuC6ZXsFxAbUkZ-QCLVQs&callback=initMap" async defer></script>

app/views/tours/search.html.erb
<div class="get-the-guide">
  <div class="container-fluid">
    <div class="row">
			<%= render partial: 'tour', collection: @tours %>
    </div>
  </div>
</div>

app/views/tours/show.html.erb
<div class="container content-container">
  <div class="row">
    <div class="col-md-6">
      <div class="row">
        <div class="col-xs-6">
          <%= image_tag('black-and-white-man-person-eyes.jpg', alt: '', class: 'img-responsive') %>
        </div>
        <div class="col-xs-6">
          <h3><%= @tour.title %></h3>
          <span class="label label-default">Language: <%= @tour.language %></span>
          <span class="label label-default">Price: $25</span>
          <span class="label label-default">Duration: 2h 30m</span>
          <span class="label label-default">Date: 25th Jul</span>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="well">
            <p>Hello, My name is Eric, I worked as a guide in 2010. I now am a licensed tour guide. I guide in Japanese, English.
              I love history, especially Paris one, I love arts, monuments, and above all gastronomy.
              I was born and raised in Paris, so I grew up here, Paris is my city.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row">
        <div class="col-xs-6">
          <% if @tour.has_coords? %>
          <img class="img-responsive" src="https://maps.googleapis.com/maps/api/staticmap?center=&zoom=13&size=500x500&maptype=roadmap&markers=color:red%7Clabel:C%7C<%= @tour.latitude %>,<%= @tour.longitude %>&key=AIzaSyCQo2TjlIearvQuC6ZXsFxAbUkZ-QCLVQs" alt="">
          <% end %>
          
        </div>
        <div class="col-xs-6">
          <img src="<%= @tour.tour_image.url %>" class="img-responsive">
        </div>
      </div>
    
    </div>
  </div>
</div>

app/views/tours/start_tour.html.erb
<div class="container content-container">
  <div class="row">
    <div class="col-md-6">
      <img class="img-responcive" src="https://maps.googleapis.com/maps/api/staticmap?center=&zoom=13&size=500x500&maptype=roadmap&markers=color:red%7Clabel:C%7C47.818217,35.998284&key=AIzaSyCQo2TjlIearvQuC6ZXsFxAbUkZ-QCLVQs" alt="">
    </div>
    <div class="col-md-6 text-center">
      <h2>Tour title</h2>
      <a href="#" class="btn btn-success btn-lg">Start tour</a>
    </div>
  </div>
</div>

app/views/tours/successful_complete.html.erb
<div class="container content-container">
  <div class="row">
    <div class="col-md-6">
      <%= image_tag('italian-building-italy-destroyed.jpg', alt: '', class: 'img-responsive') %>
    </div>
    <div class="col-md-6 text-center">
      <h2>Tour title</h2>
      <h4><small>Tourist:</small> John Smith</h4>
      <h4><small>Time:</small> 9:43 AM</h4>
      <a href="#" class="btn btn-success btn-lg">Accept call</a>
    </div>
  </div>
</div>